CREATE TABLE schedules (
                           id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                           trip_id NUMBER NOT NULL,
                           title VARCHAR2(100) NOT NULL,
                           date DATE NOT NULL,
                           start_time TIME,
                           end_time TIME,
                           location_name VARCHAR2(100) NOT NULL,
                           latitude NUMBER(10, 6) NOT NULL,
                           longitude NUMBER(10, 6) NOT NULL,
                           memo VARCHAR2(255),
                           created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
                           updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
                           PRIMARY KEY (id),
                           FOREIGN KEY (trip_id) REFERENCES trips (id)
);