-- CREATE TABLE schedules (
--                            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
--                            trip_id NUMBER NOT NULL,
--                            title VARCHAR2(100) NOT NULL,
--                            date DATE NOT NULL,
--                            start_time TIME,
--                            end_time TIME,
--                            location_name VARCHAR2(100) NOT NULL,
--                            latitude NUMBER(10, 6) NOT NULL,
--                            longitude NUMBER(10, 6) NOT NULL,
--                            memo VARCHAR2(255),
--                            created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
--                            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
--                            PRIMARY KEY (id),
--                            FOREIGN KEY (trip_id) REFERENCES trips (id)
-- );


CREATE TABLE Users (
                       UserID NUMBER(10) PRIMARY KEY,
                       Email VARCHAR2(100) UNIQUE NOT NULL,
                       Password VARCHAR2(100) NOT NULL,
                       Name VARCHAR2(50) NOT NULL,
                       Gender CHAR(1) NOT NULL,
                       Birthday DATE NOT NULL
);

CREATE TABLE UserAuth (
                          UserID NUMBER(10) PRIMARY KEY,
                          EmailAuth NUMBER(1) NOT NULL,
                          GoogleAuth NUMBER(1) NOT NULL,
                          FacebookAuth NUMBER(1) NOT NULL,
                          NaverAuth NUMBER(1) NOT NULL,
                          KakaoAuth NUMBER(1) NOT NULL,
                          FOREIGN KEY (UserID) REFERENCES Users(UserID)
);




CREATE TABLE Trip (
                      TripID NUMBER(10) PRIMARY KEY,
                      UserID NUMBER(10),
                      StartDate DATE NOT NULL,
                      EndDate DATE NOT NULL,
                      FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Place (
                       PlaceID NUMBER(10) PRIMARY KEY,
                       TripID NUMBER(10),
                       Name VARCHAR2(100) NOT NULL,
                       Address VARCHAR2(200) NOT NULL,
                       Latitude NUMBER(15, 10) NOT NULL,
                       Longitude NUMBER(15, 10) NOT NULL,
                       FOREIGN KEY (TripID) REFERENCES Trip(TripID)
);

CREATE TABLE Route (
                       RouteID NUMBER(10) PRIMARY KEY,
                       TripID NUMBER(10),
                       StartPlaceID NUMBER(10) NOT NULL,
                       EndPlaceID NUMBER(10) NOT NULL,
                       FOREIGN KEY (TripID) REFERENCES Trip(TripID),
                       FOREIGN KEY (StartPlaceID) REFERENCES Place(PlaceID),
                       FOREIGN KEY (EndPlaceID) REFERENCES Place(PlaceID)
);